config/routes.rb
Rails.application.routes.draw do
	get "/users/login", controller: "users", action: "login"
	post "/users/profile", controller: "users", action: "profile" 
	# get "/users/new", controller: "users", action: "new", as: "new_user"
	# get "/users", controller: "users", action: "index"
	# post "/users", controller: "users", action: "create"
	# get "/users/:id/edit", controller: "users", action: "edit"
	# patch "/users/:id", controller: "users", action: "update"
	# put "/users/:id", controller: "users", action: "update"
	# delete "/users/:id", controller: "users", action: "destroy"

	resources :users

	resources :questions do
		resources :question_comments
		resources :question_votes
	end

	# resources :answer_comments

	resources :answers do
		resources :answer_comments
		resources :answer_votes
	end

	root "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
	validates :answer, presence: true
  	belongs_to :user
  	belongs_to :question
  	has_many :answer_votes
  	has_many :answer_comments
end

app/models/answer_comment.rb
class AnswerComment < ApplicationRecord
	validates :comment, presence: true
  	belongs_to :user, optional: true
  	belongs_to :answer, optional: true
end

app/models/answer_vote.rb
class AnswerVote < ApplicationRecord
	belongs_to :user
	belongs_to :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	validates :question, presence: true
  	belongs_to :user
  	has_many :answers
  	has_many :question_votes
  	has_many :question_comments
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
	validates :comment, presence: true
  	belongs_to :user
  	belongs_to :question
end

app/models/question_vote.rb
class QuestionVote < ApplicationRecord
	belongs_to :user
	belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true, uniqueness: true
  	has_many :questions
  	has_many :answers
  	has_many :question_votes
  	has_many :answer_votes
  	has_many :question_comments
  	has_many :answer_comments

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

end

app/controllers/answer_comments_controller.rb
class AnswerCommentsController < ApplicationController

	def index
	end

	def new
		@answer = Answer.find_by(id: params[:answer_id])

		@answer_comment = @answer.answer_comments.new
	end

	def create
		@answer = Answer.find_by(id: params[:answer_id])
		@answer_comment = AnswerComment.new(answer_comment_params)
		@answer_comment.save

		if @answer_comment.save
			redirect_to @answer.question
		else
			render "new"
		end
	end

	private
		def answer_comment_params

			params.require(:answer_comment).permit(:comment, :user_id, :answer_id)
		end
end

app/controllers/answer_votes_controller.rb
class AnswerVotesController < ApplicationController

	def create
		@answer_vote = AnswerVote.new(user_id: 1, answer_id: params[:answer_id], up: 1, down: 0)
		@answer_vote.save

		redirect_to question_path(@answer_vote.answer.question)
	end

	def destroy
		@answer_vote = AnswerVote.where(answer_id: params[:answer_id]).last
		@answer_vote.destroy

		redirect_to question_path(@answer_vote.answer.question)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/answers_controller.rb
class AnswersController < ActionController::Base

	def new
		@answer = Answer.new
	end

	def create
		@answer = Answer.new(answer_params)

		if @answer.save
			redirect_to @answer.question
		else
			render "new"
		end
	end

	private
		def answer_params
			params.require(:answer).permit(:answer, :user_id, :question_id)
		end

end

app/controllers/question_comments_controller.rb
class QuestionCommentsController < ApplicationController

	def index
	end

	def new
		@question = Question.find_by(id: params[:question_id])

		@question_comment = @question.question_comments.new
	end

	def create
		@question = Question.find_by(id: params[:question_id])
		@question_comment = QuestionComment.new(question_comment_params)

		if @question_comment.save
			redirect_to @question_comment.question
		else
			render "new"
		end
	end

	private
		def question_comment_params
			params.require(:question_comment).permit(:comment, :user_id, :question_id)
		end

end

app/controllers/question_votes_controller.rb
class QuestionVotesController < ApplicationController

	def create
		@question_vote = QuestionVote.new(user_id: 1, question_id: params[:question_id], up: 1, down: 0)
		@question_vote.save

		if params[:page] == "show"
			redirect_to question_path(@question_vote.question)
		else
			redirect_to questions_path
		end
	end

	def destroy
		@question_vote = QuestionVote.where(question_id: params[:question_id]).last
		@question_vote.destroy

		if params[:page] == "show"
			redirect_to question_path(@question_vote.question)
		else
			redirect_to "/questions"
		end
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.all
	end

	def new
		@question = Question.new
	end

	def show
		@question = Question.find(params[:id])
	end

	def create
		@question = Question.new(question_params)

		if @question.save
			redirect_to @question
		else
			render "new"
		end
	end


	private
		def question_params
			params.require(:question).permit(:question, :user_id)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to questions_path
		else
			render "new"
		end
	end

	def login
		@user = User.new
	end

	def profile
		@user = User.find_by(email: params[:email])

		if @user
			if @user.password == params[:password]
				session[:user_id] = @user.id
			else
				render "login"
			end
		else
			render "login"
		end
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answer_comments/new.html.erb
<h1>New Answer Comment</h1>

<%= form_with model: [@answer, @answer_comment], local: true do |form| %>
	
	<% if @answer_comment.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@answer_comment.errors.count, "error") %>
					prohibitied this answerComment from being saved:
			</h2>
			<ul>
				<% @answer_comment.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= form.label :comment %>
		<%= form.text_field :comment %>
	</p>

	<p>
		<%= form.label :user_id %>
		<%= form.text_field :user_id %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/answers/new.html.erb
<h1>New answer:</h1>

<%= form_with model: @answer, local: true do |form| %>

	<% if @answer.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@answer.errors.count, "error") %>
				prohibited this article from being saved:
			</h2>
			<ul>
				<% @answer.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= form.label :answer %>
		<%= form.text_field :answer %>
	</p>

	<p>
		<%= form.label :user_id %>
		<%= form.text_field :user_id %>
	</p>

	<p>
		<%= form.label :question_id %>
		<%= form.text_field :question_id, value: params[:question_id] %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlackFloverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <%= javascript_include_tag "application" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question_comments/new.html.erb
<h1>New Question Comment:</h1>

<%= form_with model: [@question, @question_comment], local: true do |form| %>

	<% if @question_comment.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@question_comment.errors.count, "error") %>
				prohibited this questionComment from being saved:
			</h2>
			<ul>
				<% @question_comment.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= form.label :comment %>
		<%= form.text_field :comment %>
	</p>

	<p>
		<%= form.label :user_id %>
		<%= form.text_field :user_id %>
	</p>

	<p>
		<%= form.label :question_id %>
		<%= form.text_field :question_id, value: params[:question_id] %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/questions/index.html.erb
<%= link_to "Login", "users/login" %> | 
<%= link_to "Register", new_user_path %>
<br>
<%= link_to "New Question", new_question_path %>

<table>
	<tr>
		<th>Question</th>
		<th>User</th>
	</tr>

	<% @questions.each do |question| %>
		<tr>
			
			<td><%= link_to "<", question_question_votes_path(question_id: question.id), method: :post %>
			</td>
			<td><%= question.question_votes.count %></td>
			<td><%= link_to ">", question_question_vote_path(question_id: question.id, id: 1), method: :DELETE %></td>
			<td><%= question.question  %></td>
			<td><%= question.user.email %></td>
			<td><%= link_to "Show", question_path(question) %></td>
		</tr>
	<% end %>
</table>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= form_with model: @question, local: true do |form| %>

	<% if @question.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@question.errors.count, "error") %>
				prohibited this article from being saved:
			</h2>
			<ul>
				<% @question.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= form.label :question %>
		<%= form.text_field :question %>
	</p>

	<p>
		<%= form.label :user_id %>
		<%= form.text_field :user_id %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

<%= link_to "Back", questions_path %>

app/views/questions/show.html.erb
<p>
	<%= link_to "<", question_question_votes_path(question_id: @question.id, page: "show"), method: :post %>
	<%= @question.question_votes.count %>
	<%= link_to ">", question_question_vote_path(question_id: @question.id, id: 1, page: "show"), method: :DELETE %>
	<strong>Question:</strong>
	<%= @question.question %>
</p>

<p>
	<strong>User:</strong>
	<%= @question.user.email %>
	<%= link_to "Comment", controller: "question_comments", action: "new", question_id: @question %>
</p>

<% if @question.question_comments %>
	<% @question.question_comments.each do |comment| %>
		<ul>
			<li><%= comment.comment %></li>
				<ul>
					<li><%= comment.user.email %></li>
				</ul>
		</ul>
	<% end %>
<% end %>


<% if @question.answers %>
	<% @question.answers.each do |answer| %>
		<p>
			<%= link_to "<", answer_answer_votes_path(answer_id: answer.id), method: :post %>
			<%= answer.answer_votes.count %>
			<%= link_to ">", answer_answer_vote_path(answer_id: answer.id, id: 1), method: :delete %>
			<strong>Answer:</strong>
			<%= answer.answer %>
		</p>

		<p>
			<strong>User:</strong>
			<%= answer.user.email %>
			<%= link_to "Comment", controller: "answer_comments", action: "new", answer_id: answer.id %>
		</p>
		<% if answer.answer_comments %>
			<% answer.answer_comments.each do |comment| %>
				<ul>
					<li><%= comment.comment %></li>
					<ul>
						<li><%= comment.user.email %></li>
					</ul>
				</ul>
			<% end %>
		<% end %>


	<% end %>
<% end %>

<%= link_to "New Answer", controller: "answers", action: "new", question_id: @question %>
<%= link_to "Back", questions_path %>

app/views/users/login.html.erb
<%= form_with model: @users, url: "profile", method: "post", local: true do |form| %>


	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@user.errors.count, "error") %>
					prohibited this error from being saved:
			</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


	<p>
		<%= form.label :first_name %>
		<%= form.text_field :first_name %>
	</p>

	<p>
		<%= form.label :last_name %>
		<%= form.text_field :last_name %>
	</p>

	<p>
		<%= form.label :email %>
		<%= form.text_field :email %>
	</p>

	<p>
		<%= form.label :password %>
		<%= form.password_field :password %>
	</p>

	<p>
		<%= form.submit %>
	</p>


<% end %>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |form| %>
	
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@user.errors.count, "error") %>
					prohibited this user from being saved:
			</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= form.label :first_name %>
		<%= form.text_field :first_name %>
	</p>

	<p>
		<%= form.label :last_name %>
		<%= form.text_field :last_name %>
	</p>

	<p>
		<%= form.label :email %>
		<%= form.text_field :email %>
	</p>

	<p>
		<%= form.label :password %>
		<%= form.password_field :password %>
	</p>

	<p>
		<%= form.submit "Save" %>
	</p>

<% end %>

app/views/users/profile.html.erb
Hello, <%= @user.first_name %> <%= @user.last_name %>!